USE customer_behaviour;

SELECT * FROM customer;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender,SUM(purchase_amount) as total_amount
FROM customer
GROUP BY gender;

-- Q2. Which customer used discounted applied but still spent more than the average purchase amount.
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'YES' and purchase_amount >(SELECT AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 product with highest avereage review rating?
SELECT item_purchased,ROUND(AVG(review_rating),2) AS review_rating
FROM customer
GROUP BY item_purchased
ORDER BY review_rating DESC
LIMIT 5;

-- Q4. Top performing items in each category based on the season.

WITH sales as
(
SELECT season,category,item_purchased,COUNT(*) AS total_sold, SUM(purchase_amount) AS total_revenue_generated
FROM customer
GROUP BY season,category,item_purchased
)

SELECT * 
FROM
   (SELECT *,
   RANK() OVER (PARTITION BY season ORDER BY total_revenue_generated DESC) as ranking
   FROM sales)t WHERE ranking <= 3;

-- Q5. Compare the Average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE  shipping_type in ('Express', 'Standard')
GROUP BY shipping_type;

-- Here we can understand avg purchase amount is higher for express shipping type compared to standard.The business should focus on Express shipping and other for faster delivery option.

-- Q6. Do Subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT subscription_status,
COUNT(customer_id) as total_customers,
AVG(purchase_amount) as avg_spend,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status;

-- Q7. Which 5 products have highest percentage of purchase with discount applied?
-- Here we find the discount rate per product.Which product rely heavily on discount to sell.

SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) *100, 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
 -- Here we are finding the percentage of times discount applied to an item.
 -- Basically if a hat was sold 10 times 50% of the time which means 5 times the hat was sold with a discount.
 
 -- Q8. Group customers into New, Returning, Loyal based on their purchases,and show the count of each segment.
 WITH customer_type as
 (
 SELECT customer_id,previous_purchases,
 CASE WHEN previous_purchases = 1 THEN 'NEW'
	  WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
      ELSE 'LOYAL'
END customer_segment
FROM customer
)
SELECT customer_segment,COUNT(*) AS total_customer
FROM customer_type
GROUP BY customer_segment;    

-- Q9. What are the top 3 most purchased products within each category. 
WITH top_products as
(
SELECT category,item_purchased ,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS ranking
FROM customer
GROUP BY category,item_purchased
)
SELECT *
FROM top_products
WHERE ranking <= 3;

-- Q10. Are customers who are repeat buyers (more than 5 previous purchases) also likely to be subscribed?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- This is very powerful metrices.Because customers who are repeat buyers and take subsciption is great for the business.
-- But customers who are loyal and not take the subscription means the subsciption offer isn't attractive for the customers.

-- Q11. What is the revenue contribution by each age group?
SELECT 
age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
 

